/**
 * The entry screen: create a vault, unlock it, or recover it.
 *
 * This is the first thing a user sees after clicking "Open the vault", so every
 * branch a person can actually take has to be here. The previous version had
 * two of the three:
 *
 *  - A wrong password produced the raw WebCrypto message "The operation failed
 *    for an operation-specific reason", which tells someone nothing. The server
 *    now returns a `code`, so this branches on `wrong_password` instead of on
 *    English prose.
 *  - Recovery did not exist at all, even though `POST /recover` and a BIP39
 *    generator had been in the codebase all along. A vault that advertised a
 *    recovery phrase it could never use was worse than not advertising one.
 *  - Setup took the phrase as optional free text and checked nothing, so a vault
 *    could be created whose only way back in was a typo. The phrase is now
 *    generated by the server, validated, and confirmed before setup completes.
 *
 * `onUnlocked` fires only once the vault is actually open, so the parent can
 * treat it as "you are in" rather than re-deriving it.
 *
 * `Frame` deliberately renders no interactive element. The touch-target suite
 * asserts that the not-connected screen has exactly one control, and that
 * screen is this frame plus a single button, so a wordmark link or a "back to
 * the site" affordance added here would be a test failure.
 */
import React, { useCallback, useEffect, useState } from 'react';
import { useTranslation } from 'react-i18next';
import { AlertTriangle, KeyRound, Lock, ShieldCheck, Terminal } from 'lucide-react';
import { api, isConnected } from './api';

type Mode = 'unlock' | 'create' | 'recover';

const TAP_TARGET = 'min-h-[44px]';

/** Reads the server's error code into a translated message. */
const useErrorMessage = () => {
  const { t } = useTranslation();
  return (error: { message: string; code: string | null } | null): string => {
    if (!error) return '';
    const translated = error.code ? t(`errors:${error.code}`) : undefined;
    // i18next echoes the key back when a code is missing from the catalogue,
    // so anything still shaped like `errors:...` means "no translation".
    return translated && !translated.startsWith('errors:') ? translated : error.message;
  };
};

/**
 * Shared field chrome.
 *
 * No `min-height` here on purpose. The one-line inputs and the taller recovery
 * textarea share this string, and two `min-h-[…]` utilities on one element
 * resolve by stylesheet order rather than by attribute order, so the winner
 * would depend on how Tailwind happened to sort the two arbitrary values. Each
 * caller states its own floor instead.
 */
const INPUT =
  'w-full rounded-xl border border-line bg-ink-soft px-4 py-3 text-sm text-cream placeholder:text-faint focus:border-sand';

export const LockScreen: React.FC<{
  /** False when no server is reachable, which changes the call to action. */
  hasVault: boolean | null;
  onUnlocked: () => void;
  onDisconnect: () => void;
}> = ({ hasVault, onUnlocked, onDisconnect }) => {
  const { t } = useTranslation();
  const errorText = useErrorMessage();

  const [mode, setMode] = useState<Mode>(hasVault === false ? 'create' : 'unlock');
  const [password, setPassword] = useState('');
  const [confirmPassword, setConfirmPassword] = useState('');
  const [phrase, setPhrase] = useState('');
  const [recoveryInput, setRecoveryInput] = useState('');
  const [phraseSaved, setPhraseSaved] = useState(false);
  const [copied, setCopied] = useState(false);
  const [error, setError] = useState<{ message: string; code: string | null } | null>(null);
  const [busy, setBusy] = useState(false);

  // A fresh vault needs a recovery phrase, and it has to come from the server
  // so the BIP39 wordlist stays out of this bundle. Generated up front so the
  // user can read it before the password fields matter.
  useEffect(() => {
    if (mode !== 'create' || phrase) return;
    let cancelled = false;
    void api.generateRecovery().then((res) => {
      if (!cancelled && res.data) setPhrase(res.data);
    });
    return () => {
      cancelled = true;
    };
  }, [mode, phrase]);

  const submit = useCallback(
    async (event: React.FormEvent) => {
      event.preventDefault();
      setError(null);

      if (mode === 'create') {
        if (password.length < 12) {
          setError({ message: t('lock.passwordTooShort'), code: null });
          return;
        }
        if (password !== confirmPassword) {
          setError({ message: t('lock.passwordMismatch'), code: null });
          return;
        }
        if (!phraseSaved) {
          setError({ message: t('lock.recoveryRequired'), code: null });
          return;
        }
      }

      setBusy(true);
      try {
        const res =
          mode === 'create'
            ? await api.setup(password, phrase)
            : mode === 'recover'
              ? await api.recover(recoveryInput.trim())
              : await api.unlock(password);

        if (res.error) {
          setError({ message: res.error.message, code: res.error.code });
          return;
        }
        onUnlocked();
      } finally {
        setBusy(false);
      }
    },
    [mode, password, confirmPassword, phrase, phraseSaved, recoveryInput, onUnlocked, t]
  );

  const words = phrase ? phrase.split(/\s+/) : [];

  if (!isConnected()) {
    return (
      <Frame
        icon={<Terminal size={30} />}
        title={t('lock.notConnected')}
        body={t('lock.notConnectedHint')}
      >
        <button type="button" onClick={onDisconnect} className="btn btn-sand w-full">
          {t('lock.connect')}
        </button>
      </Frame>
    );
  }

  return (
    <Frame
      icon={<ShieldCheck size={30} />}
      title={mode === 'recover' ? t('lock.recoveryTitle') : t('lock.title')}
      body={mode === 'recover' ? t('lock.recoverySubtitle') : t('lock.subtitle')}
    >
      {mode === 'create' && (
        <RecoveryPhraseSetup
          words={words}
          copied={copied}
          phraseSaved={phraseSaved}
          onCopy={() => {
            void navigator.clipboard?.writeText(phrase).catch(() => {});
            setCopied(true);
          }}
          onSaved={setPhraseSaved}
        />
      )}

      <form onSubmit={submit} className="space-y-5">
        {error && (
          <div role="alert" className="rounded-xl border border-alert/35 bg-alert/10 p-3 text-sm leading-relaxed text-alert">
            {errorText(error)}
          </div>
        )}

        {mode === 'create' && (
          <p className="rounded-xl border border-sand/30 bg-sand/10 p-3 text-sm leading-relaxed text-sand">
            {t('lock.newVaultDetected')}
          </p>
        )}

        {mode === 'recover' ? (
          <Field label={t('lock.recoveryTitle')}>
            <textarea
              autoFocus
              rows={3}
              value={recoveryInput}
              onChange={(e) => setRecoveryInput(e.target.value)}
              placeholder={t('lock.recoveryPlaceholder')}
              spellCheck={false}
              autoComplete="off"
              className={`${INPUT} min-h-[104px] resize-none font-mono`}
            />
          </Field>
        ) : (
          <>
            <Field label={t('lock.masterPassword')}>
              <input
                type="password"
                autoFocus
                value={password}
                onChange={(e) => setPassword(e.target.value)}
                autoComplete={mode === 'create' ? 'new-password' : 'current-password'}
                className={`${INPUT} min-h-[44px] tracking-widest`}
              />
            </Field>

            {mode === 'create' && (
              <Field label={t('lock.confirmPassword')}>
                <input
                  type="password"
                  value={confirmPassword}
                  onChange={(e) => setConfirmPassword(e.target.value)}
                  autoComplete="new-password"
                  className={`${INPUT} min-h-[44px] tracking-widest`}
                />
              </Field>
            )}
          </>
        )}

        <button
          type="submit"
          disabled={busy}
          className={`btn w-full disabled:opacity-60 ${mode === 'create' ? 'btn-sand' : 'border border-line text-cream hover:border-sand/60 hover:text-sand'}`}
        >
          {mode === 'unlock' && <Lock size={16} />}
          {busy
            ? t(
                mode === 'unlock'
                  ? 'lock.unlocking'
                  : mode === 'recover'
                    ? 'lock.recovering'
                    : 'lock.creating'
              )
            : mode === 'create'
              ? t('lock.createVault')
              : mode === 'recover'
                ? t('lock.recover')
                : t('lock.unlock')}
        </button>
      </form>

      {/* Both of these are the paths people search for at the worst moment, so
          they are on the screen rather than buried in a menu. */}
      {mode === 'unlock' && (
        <button
          type="button"
          onClick={() => {
            setMode('recover');
            setError(null);
          }}
          className={`w-full ${TAP_TARGET} py-2 text-center text-sm text-sand hover:text-sand-deep`}
        >
          {t('lock.useRecovery')}
        </button>
      )}
      {mode !== 'unlock' && (
        <button
          type="button"
          onClick={() => {
            setMode(hasVault ? 'unlock' : 'create');
            setError(null);
          }}
          className={`w-full ${TAP_TARGET} py-2 text-center text-sm text-sand hover:text-sand-deep`}
        >
          {t('lock.backToPassword')}
        </button>
      )}

      <button
        type="button"
        onClick={onDisconnect}
        className={`w-full ${TAP_TARGET} py-2 text-center text-xs text-faint hover:text-muted`}
      >
        {t('lock.changeConnection')}
      </button>

      <p className="border-t border-line pt-4 text-[11px] leading-relaxed text-faint">{t('vault.sessionOnly')}</p>
    </Frame>
  );
};

/**
 * The generated recovery phrase.
 *
 * Shown as a numbered grid rather than a sentence because people copy these by
 * hand and transcription errors are the whole failure mode. Confirmation is a
 * gate, not a nudge: there is no way to finish setup without it, because a
 * vault whose only recovery path is unchecked free text is unrecoverable.
 */
const RecoveryPhraseSetup: React.FC<{
  words: string[];
  copied: boolean;
  phraseSaved: boolean;
  onCopy: () => void;
  onSaved: (saved: boolean) => void;
}> = ({ words, copied, phraseSaved, onCopy, onSaved }) => {
  const { t } = useTranslation();

  return (
    <section className="space-y-3">
      <div className="eyebrow flex items-center gap-2 text-sand">
        <KeyRound size={12} />
        {t('lock.stepRecovery')}
      </div>

      <p className="text-[13px] leading-relaxed text-muted">{t('lock.recoveryIntro')}</p>

      {words.length > 0 ? (
        <ol className="grid grid-cols-3 gap-x-3 gap-y-2 rounded-xl border border-line bg-ink-soft p-4">
          {words.map((word, i) => (
            <li key={`${word}-${i}`} className="flex min-w-0 items-baseline gap-2 text-sm">
              <span className="w-4 shrink-0 text-[10px] text-faint tabular-nums">{i + 1}</span>
              <span className="truncate font-mono text-cream">{word}</span>
            </li>
          ))}
        </ol>
      ) : (
        <div className="flex h-[92px] items-center justify-center rounded-xl border border-line bg-ink-soft text-xs text-faint">
          {t('lock.recovering')}...
        </div>
      )}

      {words.length > 0 && (
        <button
          type="button"
          onClick={onCopy}
          className={`w-full ${TAP_TARGET} py-1 text-xs text-sand hover:text-sand-deep`}
        >
          {copied ? t('lock.phraseCopied') : t('common.copy')}
        </button>
      )}

      <label className="flex cursor-pointer items-start gap-3 rounded-xl border border-sand/30 bg-sand/10 p-3">
        <input
          type="checkbox"
          checked={phraseSaved}
          onChange={(e) => onSaved(e.target.checked)}
          className="mt-0.5 h-4 w-4 shrink-0 accent-sand"
        />
        <span className="flex items-start gap-1.5 text-sm leading-relaxed text-sand">
          <AlertTriangle size={14} className="mt-0.5 shrink-0" />
          {t('lock.recoverySaved')}
        </span>
      </label>
    </section>
  );
};

const Field: React.FC<{ label: string; children: React.ReactNode }> = ({ label, children }) => (
  <div className="space-y-2">
    <label className="eyebrow block text-faint">{label}</label>
    {children}
  </div>
);

/**
 * The card every branch of this screen sits in.
 *
 * It renders no interactive element on purpose, see the note at the top of the
 * file: the touch-target suite counts the controls on the not-connected branch.
 */
const Frame: React.FC<{ icon: React.ReactNode; title: string; body: string; children: React.ReactNode }> = ({
  icon,
  title,
  body,
  children,
}) => (
  <div className="hero-field flex min-h-screen w-screen items-center justify-center p-5">
    <div className="glass w-full max-w-md rounded-2xl p-8 shadow-lift">
      <div className="mb-8 flex flex-col items-center text-center">
        <div className="text-sand">{icon}</div>
        <h1 className="font-display mt-5 text-[1.75rem] leading-tight text-cream">{title}</h1>
        <p className="mt-3 max-w-xs text-[13px] leading-relaxed text-muted">{body}</p>
      </div>
      <div className="space-y-5">{children}</div>
    </div>
  </div>
);