name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '🚀 Fitur Baru'
    labels:
      - 'enhancement'
      - 'feature'
  - title: '🐛 Perbaikan Bug'
    labels:
      - 'bug'
      - 'fix'
  - title: '⚡ Optimasi & Performa'
    labels:
      - 'performance'
      - 'perf'
  - title: '📝 Dokumentasi'
    labels:
      - 'documentation'
      - 'docs'
  - title: '🏠 Internal & Refactor'
    labels:
      - 'internal'
      - 'refactor'
      - 'chore'
change-template: '- $TITLE (#$NUMBER) @$AUTHOR'
template: |
  ## Apa yang Baru?
  
  $CHANGES
