services:
  lembaranz:
    build:
      context: .
      dockerfile: Dockerfile
    image: lembaranz:latest
    container_name: lembaranz-app
    ports:
      - "1400:1400"
    volumes:
      - lembaranz-data:/app/data
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
      - DB_PATH=/app/data/.lembaranz-db.json
    restart: always

volumes:
  lembaranz-data:
