services:
  lembaranzz:
    build:
      context: .
      dockerfile: Dockerfile
    image: lembaranzz:latest
    container_name: lembaranzz-app
    ports:
      - "1400:1400"
    volumes:
      - lembaranzz-data:/app/data
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
      - DB_PATH=/app/data/.lembaranzz-db.json
    restart: always

volumes:
  lembaranzz-data:
